'''
Mapping for the data
'''
mappings = {
    'damage': {
        0: 'Minimal Damage (<1%)',
        1: 'Noticeable Damange (1-9%)',
        2: 'Minor Damange (10-25%)',
        3: 'Destroyed (>50%)',
        4: 'Majorly Destroyed (26-50%)',
        5: 'Totally Destroyed'
    },
    'street_type': {
        0: 'Road',
        1: 'Lane',
        2: 'Other',
        3: 'Trail',
        4: 'Drive',
        5: 'Street',
        6: 'None',
        7: 'Way',
        8: 'Avenue',
        9: 'Court',
        10: 'Loop',
        11: 'Route',
        12: 'Place',
        13: 'Alley',
        14: 'Terrace',
        15: 'Circle',
        16: 'Boulevard',
        17: 'Parkway',
        19: ' ',
        20: 'Hwy',
        21: 'Dirt road',
        22: '-',
        23: 'not given',
        24: 'Grade',
        25: 'Ext.',
        26: 'not noted',
        27: 'Unk',
        28: 'Pass'
    },
    'fire_unit': {
        0: 'LNU',
        1: 'AEU',
        2: 'BTU',
        3: 'SLU',
        4: 'SKU',
        5: 'SCU',
        6: 'BEU',
        7: 'LMU',
        8: 'RRU',
        9: 'BDU',
        10: 'KRN',
        11: 'NEU',
        12: 'SHU',
        13: 'TGU',
        14: 'LAC',
        15: 'MEU',
        16: 'MVU',
        17: 'HUU',
        18: 'TUU',
        19: 'FKU',
        20: 'MMU',
        21: 'CZU',
        22: 'ORC',
        23: 'VNC',
        24: 'TCU',
        25: 'SBC',
        26: 'SDU'
    },
    'structure_type': {
        0: 'Single Family Residence Multi Story',
        1: 'Single Family Residence Single Story',
        2: 'Utility Misc Structure',
        3: 'Mobile Home Double Wide',
        4: 'Motor Home',
        5: 'Multi Family Residence Multi Story',
        6: 'Commercial Building Single Story',
        7: 'Mobile Home Single Wide',
        8: 'Mixed Commercial/Residential',
        9: 'Mobile Home Triple Wide',
        10: 'Infrastructure',
        11: 'School',
        12: 'Multi Family Residence Single Story',
        13: 'Commercial Building Multi Story',
        14: 'Church',
        15: 'Hospital',
        16: 'Agriculture',
        17: 'Single Famliy Residence Single Story',
        18: 'Utility or Miscellaneous Structure > 120 sqft'
    },
    'structure_category': {
        0: 'Single Residence',
        1: 'Other Minor Structure',
        2: 'Multiple Residence',
        3: 'Nonresidential Commercial',
        4: 'Mixed Commercial/Residential',
        5: 'Infrastructure',
        6: 'Agriculture'
    },
    'roof_material': {
        0: 'Asphalt',
        1: 'Tile',
        2: 'Unknown',
        3: 'Metal',
        4: 'Concrete',
        5: 'Other',
        6: 'Wood',
        7: ' ',
        8: 'Combustible',
        9: 'Fire Resistant',
        11: 'No Deck/Porch'
    },
    'eaves': {
        0: 'Unenclosed',
        1: 'Enclosed',
        2: 'Unknown',
        3: 'No Eaves',
        4: ' ',
        5: 'Not Applicable'
    },
    'exterior_siding': {
        0: 'Wood',
        1: 'Stucco Brick Cement',
        2: 'Unknown',
        3: 'Metal',
        4: 'Other',
        5: 'Vinyl',
        6: 'Ignition Resistant',
        7: 'Combustible',
        8: ' ',
        9: 'Fire Resistant',
        11: 'Stucco/Brick/Cement'
    },
    'window_pane': {
        0: 'Single Pane',
        1: 'Multi Pane',
        2: 'Unknown',
        3: 'No Windows',
        4: ' ',
        6: 'No Deck/Porch',
        7: 'Radiant Heat'
    },
    'attached_patio_material': {
        0: 'No Patio Cover/Carport',
        1: 'Combustible',
        2: 'Unknown',
        3: 'Non Combustible',
        4: ' '
    },
    'attached_fence_material': {
        0: 'No Fence',
        1: 'Combustible',
        2: 'Unknown',
        3: 'Non Combustible'
    }
}
